### ISSUE TITLE
'retweet' functionality 

### ISSUE THREAD

**Issue by coreymalek** [robert-hatfield/twitter-client#6] opened 2017-03-23 18:03 UTC
It looks like you have your UI set up to display an indication of a retweet, however it appears we're just missing a bit of functionality to get that to display. Overall great job though!

**Comment by robert-hatfield** [comment] 2017-03-23 19:41
That should be working... if the tweet _is_ a retweet by a user you're following, a "RETWEET" label appears on the detail view. (It won't display if that tweet is "original" and has been retweeted by other Twitter users.)
Look for any tweet text that starts with "RT" - that seems to be a common indicator.

**Comment by robert-hatfield** [comment] 2017-03-24 15:08
Confirmed as working - closing issue.

**Closed as completed by robert-hatfield** 2017-03-24 15:08 UTC
